services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: front-end:latest
    environment:
      - VITE_KEYCLOAK_URL=http://kdg_idp_keycloak:8180
      - VITE_KEYCLOAK_REALM=Rummikub
      - VITE_KEYCLOAK_CLIENT_ID=RummikubApp
      - VITE_KEYCLOAK_CLIENT_SECRET=Tv95wGLAPuFhdULOUaixLIaAu4XCFCvh
      - VITE_BACKEND_URL=http://backend:8080
      - VITE_REACT_APP_URL=http://localhost:4000
    ports:
    - '3000:3000'


