services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: front-end:latest
    environment:
      APP_ENV_PREFIX: REACT_APP_
      REACT_APP_KEYCLOAK_URL: http://kdg_idp_keycloak:8180
      REACT_APP_KEYCLOAK_REALM: Rummikub
      REACT_APP_KEYCLOAK_CLIENT_ID: RummikubApp
      REACT_APP_KEYCLOAK_CLIENT_SECRET: Tv95wGLAPuFhdULOUaixLIaAu4XCFCvh
      REACT_APP_BACKEND_URL: http://backend:8080
      REACT_APP_REACT_APP_URL: http://localhost:4000
    ports:
    - '3000:3000'
